@startuml
'https://plantuml.com/class-diagram

class App {
+main( String[] args )

+parseJsonFile()

class productDetails {
String name
double price
int quantity
}

class JsonParse {
productDetails()

}


@enduml